import { GlobalStyle } from "../../styles/globals"
import Head from 'next/head';

export default function Layout(props){

    return (
        <div className='layout bg'>
            <Head>
                <title>Meu Hype</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <GlobalStyle/>
            { props.children }
        </div>
    )
}